// Catálogo oficial de libros a la venta (99 libros reales con ISBN valorados)
// Generado automáticamente a partir de 'Inventario Libros en Venta con ISBN - Untitled.csv'

export type CatalogBook = {
  slug: string;
  title: string;
  author: string;
  isbn: string;
  price: number;
  genre: string;
  imageUrl: string;
  imageAlt: string;
  amazonUrl: string;
};

export const catalogBooks: CatalogBook[] = [
  {
    "slug": "a-la-izquierda-de-la-escalera",
    "title": "A la izquierda de la escalera",
    "author": "Halasi, Kun",
    "isbn": "978-8424158422",
    "price": 4.9,
    "genre": "Juvenil",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788424158422-L.jpg",
    "imageAlt": "Portada de A la izquierda de la escalera, de Halasi, Kun",
    "amazonUrl": "https://www.amazon.es/s?k=A%20la%20izquierda%20de%20la%20escalera%20Halasi%2C%20Kun&tag=libreriajerez-21"
  },
  {
    "slug": "cinco-dias-de-agosto",
    "title": "Cinco días de agosto",
    "author": "Hester Burton",
    "isbn": "978-8427931398",
    "price": 4.9,
    "genre": "Juvenil / Ficción histórica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788427931398-L.jpg",
    "imageAlt": "Portada de Cinco días de agosto, de Hester Burton",
    "amazonUrl": "https://www.amazon.es/s?k=Cinco%20d%C3%ADas%20de%20agosto%20Hester%20Burton&tag=libreriajerez-21"
  },
  {
    "slug": "el-gato-mog",
    "title": "El gato Mog",
    "author": "Joan Aiken",
    "isbn": "978-8427931145",
    "price": 4.9,
    "genre": "Infantil / Juvenil",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788427931145-L.jpg",
    "imageAlt": "Portada de El gato Mog, de Joan Aiken",
    "amazonUrl": "https://www.amazon.es/s?k=El%20gato%20Mog%20Joan%20Aiken&tag=libreriajerez-21"
  },
  {
    "slug": "la-otra-casa",
    "title": "La otra casa",
    "author": "J. L. Giménez-Frontín",
    "isbn": "978-8427931558",
    "price": 4.9,
    "genre": "Juvenil",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788427931558-L.jpg",
    "imageAlt": "Portada de La otra casa, de J. L. Giménez-Frontín",
    "amazonUrl": "https://www.amazon.es/s?k=La%20otra%20casa%20J.%20L.%20Gim%C3%A9nez-Front%C3%ADn&tag=libreriajerez-21"
  },
  {
    "slug": "zuleika-dobson",
    "title": "Zuleika Dobson",
    "author": "Max Beerbohm",
    "isbn": "978-8478446056",
    "price": 5.5,
    "genre": "Sátira / Clásicos",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788478446056-L.jpg",
    "imageAlt": "Portada de Zuleika Dobson, de Max Beerbohm",
    "amazonUrl": "https://www.amazon.es/s?k=Zuleika%20Dobson%20Max%20Beerbohm&tag=libreriajerez-21"
  },
  {
    "slug": "moriras-en-chafarinas",
    "title": "Morirás en Chafarinas",
    "author": "Fernando Lalana",
    "isbn": "978-8467582574",
    "price": 4.9,
    "genre": "Juvenil / Policiaco",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788467582574-L.jpg",
    "imageAlt": "Portada de Morirás en Chafarinas, de Fernando Lalana",
    "amazonUrl": "https://www.amazon.es/s?k=Morir%C3%A1s%20en%20Chafarinas%20Fernando%20Lalana&tag=libreriajerez-21"
  },
  {
    "slug": "los-escarabajos-vuelan-al-atardecer",
    "title": "Los escarabajos vuelan al atardecer",
    "author": "Maria Gripe",
    "isbn": "978-8424681029",
    "price": 4.9,
    "genre": "Juvenil / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788424681029-L.jpg",
    "imageAlt": "Portada de Los escarabajos vuelan al atardecer, de Maria Gripe",
    "amazonUrl": "https://www.amazon.es/s?k=Los%20escarabajos%20vuelan%20al%20atardecer%20Maria%20Gripe&tag=libreriajerez-21"
  },
  {
    "slug": "los-espejos-venecianos",
    "title": "Los espejos venecianos",
    "author": "Joan Manuel Gisbert",
    "isbn": "978-8426348463",
    "price": 4.9,
    "genre": "Juvenil / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788426348463-L.jpg",
    "imageAlt": "Portada de Los espejos venecianos, de Joan Manuel Gisbert",
    "amazonUrl": "https://www.amazon.es/s?k=Los%20espejos%20venecianos%20Joan%20Manuel%20Gisbert&tag=libreriajerez-21"
  },
  {
    "slug": "el-escritor-asesino",
    "title": "El escritor asesino",
    "author": "Blanca Álvarez",
    "isbn": "978-8426349323",
    "price": 4.9,
    "genre": "Juvenil / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788426349323-L.jpg",
    "imageAlt": "Portada de El escritor asesino, de Blanca Álvarez",
    "amazonUrl": "https://www.amazon.es/s?k=El%20escritor%20asesino%20Blanca%20%C3%81lvarez&tag=libreriajerez-21"
  },
  {
    "slug": "donde-esta-mi-corazon",
    "title": "Dónde está mi corazón",
    "author": "Jordi Sierra i Fabra",
    "isbn": "978-8424681654",
    "price": 4.9,
    "genre": "Juvenil / Drama",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788424681654-L.jpg",
    "imageAlt": "Portada de Dónde está mi corazón, de Jordi Sierra i Fabra",
    "amazonUrl": "https://www.amazon.es/s?k=D%C3%B3nde%20est%C3%A1%20mi%20coraz%C3%B3n%20Jordi%20Sierra%20i%20Fabra&tag=libreriajerez-21"
  },
  {
    "slug": "eva-luna",
    "title": "Eva Luna",
    "author": "Isabel Allende",
    "isbn": "978-8401342196",
    "price": 5.9,
    "genre": "Narrativa",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788401342196-L.jpg",
    "imageAlt": "Portada de Eva Luna, de Isabel Allende",
    "amazonUrl": "https://www.amazon.es/s?k=Eva%20Luna%20Isabel%20Allende&tag=libreriajerez-21"
  },
  {
    "slug": "los-viajes-de-gulliver",
    "title": "Los viajes de Gulliver",
    "author": "Jonathan Swift",
    "isbn": "978-8420660608",
    "price": 5.5,
    "genre": "Clásicos / Sátira",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420660608-L.jpg",
    "imageAlt": "Portada de Los viajes de Gulliver, de Jonathan Swift",
    "amazonUrl": "https://www.amazon.es/s?k=Los%20viajes%20de%20Gulliver%20Jonathan%20Swift&tag=libreriajerez-21"
  },
  {
    "slug": "viaje-al-centro-de-la-tierra",
    "title": "Viaje al centro de la Tierra",
    "author": "Julio Verne",
    "isbn": "978-8420664422",
    "price": 5.5,
    "genre": "Clásicos / Aventuras",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420664422-L.jpg",
    "imageAlt": "Portada de Viaje al centro de la Tierra, de Julio Verne",
    "amazonUrl": "https://www.amazon.es/s?k=Viaje%20al%20centro%20de%20la%20Tierra%20Julio%20Verne&tag=libreriajerez-21"
  },
  {
    "slug": "el-senor-de-las-moscas",
    "title": "El señor de las moscas",
    "author": "William Golding",
    "isbn": "978-8420674179",
    "price": 5.5,
    "genre": "Narrativa / Clásicos",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420674179-L.jpg",
    "imageAlt": "Portada de El señor de las moscas, de William Golding",
    "amazonUrl": "https://www.amazon.es/s?k=El%20se%C3%B1or%20de%20las%20moscas%20William%20Golding&tag=libreriajerez-21"
  },
  {
    "slug": "el-monje-que-vendio-su-ferrari",
    "title": "El monje que vendió su Ferrari",
    "author": "Robin Sharma",
    "isbn": "978-8466332903",
    "price": 5.5,
    "genre": "Autoayuda / Crecimiento",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788466332903-L.jpg",
    "imageAlt": "Portada de El monje que vendió su Ferrari, de Robin Sharma",
    "amazonUrl": "https://www.amazon.es/s?k=El%20monje%20que%20vendi%C3%B3%20su%20Ferrari%20Robin%20Sharma&tag=libreriajerez-21"
  },
  {
    "slug": "etica-para-amador",
    "title": "Ética para Amador",
    "author": "Fernando Savater",
    "isbn": "978-8434412217",
    "price": 7.5,
    "genre": "Ensayo / Filosofía",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788434412217-L.jpg",
    "imageAlt": "Portada de Ética para Amador, de Fernando Savater",
    "amazonUrl": "https://www.amazon.es/s?k=%C3%89tica%20para%20Amador%20Fernando%20Savater&tag=libreriajerez-21"
  },
  {
    "slug": "rebelion-en-la-granja",
    "title": "Rebelión en la granja",
    "author": "George Orwell",
    "isbn": "978-8499890944",
    "price": 5.5,
    "genre": "Sátira / Ficción",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788499890944-L.jpg",
    "imageAlt": "Portada de Rebelión en la granja, de George Orwell",
    "amazonUrl": "https://www.amazon.es/s?k=Rebeli%C3%B3n%20en%20la%20granja%20George%20Orwell&tag=libreriajerez-21"
  },
  {
    "slug": "el-camino",
    "title": "El camino",
    "author": "Miguel Delibes",
    "isbn": "978-8423342709",
    "price": 5.5,
    "genre": "Narrativa / Clásicos",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788423342709-L.jpg",
    "imageAlt": "Portada de El camino, de Miguel Delibes",
    "amazonUrl": "https://www.amazon.es/s?k=El%20camino%20Miguel%20Delibes&tag=libreriajerez-21"
  },
  {
    "slug": "diario-de-una-buena-vecina",
    "title": "Diario de una buena vecina",
    "author": "Doris Lessing",
    "isbn": "978-8497939102",
    "price": 5.9,
    "genre": "Narrativa contemporánea",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497939102-L.jpg",
    "imageAlt": "Portada de Diario de una buena vecina, de Doris Lessing",
    "amazonUrl": "https://www.amazon.es/s?k=Diario%20de%20una%20buena%20vecina%20Doris%20Lessing&tag=libreriajerez-21"
  },
  {
    "slug": "el-coronel-no-tiene-quien-le-escriba",
    "title": "El coronel no tiene quien le escriba",
    "author": "Gabriel García Márquez",
    "isbn": "978-8497592352",
    "price": 5.5,
    "genre": "Narrativa / Clásicos",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497592352-L.jpg",
    "imageAlt": "Portada de El coronel no tiene quien le escriba, de Gabriel García Márquez",
    "amazonUrl": "https://www.amazon.es/s?k=El%20coronel%20no%20tiene%20quien%20le%20escriba%20Gabriel%20Garc%C3%ADa%20M%C3%A1rquez&tag=libreriajerez-21"
  },
  {
    "slug": "memoria-de-mis-putas-tristes",
    "title": "Memoria de mis putas tristes",
    "author": "Gabriel García Márquez",
    "isbn": "978-8497599894",
    "price": 5.5,
    "genre": "Narrativa",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497599894-L.jpg",
    "imageAlt": "Portada de Memoria de mis putas tristes, de Gabriel García Márquez",
    "amazonUrl": "https://www.amazon.es/s?k=Memoria%20de%20mis%20putas%20tristes%20Gabriel%20Garc%C3%ADa%20M%C3%A1rquez&tag=libreriajerez-21"
  },
  {
    "slug": "el-cartero-siempre-llama-mil-veces",
    "title": "El cartero siempre llama mil veces",
    "author": "Andreu Martín y Jaume Ribera",
    "isbn": "978-8420743912",
    "price": 5.9,
    "genre": "Novela negra / Humor",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420743912-L.jpg",
    "imageAlt": "Portada de El cartero siempre llama mil veces, de Andreu Martín y Jaume Ribera",
    "amazonUrl": "https://www.amazon.es/s?k=El%20cartero%20siempre%20llama%20mil%20veces%20Andreu%20Mart%C3%ADn%20y%20Jaume%20Ribera&tag=libreriajerez-21"
  },
  {
    "slug": "un-viejo-que-leia-novelas-de-amor",
    "title": "Un viejo que leía novelas de amor",
    "author": "Luis Sepúlveda",
    "isbn": "978-8483835234",
    "price": 5.9,
    "genre": "Narrativa",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788483835234-L.jpg",
    "imageAlt": "Portada de Un viejo que leía novelas de amor, de Luis Sepúlveda",
    "amazonUrl": "https://www.amazon.es/s?k=Un%20viejo%20que%20le%C3%ADa%20novelas%20de%20amor%20Luis%20Sep%C3%BAlveda&tag=libreriajerez-21"
  },
  {
    "slug": "brumas-de-octubre",
    "title": "Brumas de octubre",
    "author": "Lola González",
    "isbn": "978-8420448770",
    "price": 4.9,
    "genre": "Juvenil / Ficción",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420448770-L.jpg",
    "imageAlt": "Portada de Brumas de octubre, de Lola González",
    "amazonUrl": "https://www.amazon.es/s?k=Brumas%20de%20octubre%20Lola%20Gonz%C3%A1lez&tag=libreriajerez-21"
  },
  {
    "slug": "el-primer-amor",
    "title": "El primer amor",
    "author": "Iván Turguénev",
    "isbn": "978-8420663401",
    "price": 5.5,
    "genre": "Clásicos",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420663401-L.jpg",
    "imageAlt": "Portada de El primer amor, de Iván Turguénev",
    "amazonUrl": "https://www.amazon.es/s?k=El%20primer%20amor%20Iv%C3%A1n%20Turgu%C3%A9nev&tag=libreriajerez-21"
  },
  {
    "slug": "el-bosque-encantado",
    "title": "El bosque encantado",
    "author": "Victoria Holt",
    "isbn": "978-8422616221",
    "price": 5.5,
    "genre": "Novela gótica / Romántica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788422616221-L.jpg",
    "imageAlt": "Portada de El bosque encantado, de Victoria Holt",
    "amazonUrl": "https://www.amazon.es/s?k=El%20bosque%20encantado%20Victoria%20Holt&tag=libreriajerez-21"
  },
  {
    "slug": "el-traidor-del-siglo",
    "title": "El traidor del siglo",
    "author": "John le Carré",
    "isbn": "978-8401328329",
    "price": 6.5,
    "genre": "Espionaje / Suspense",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788401328329-L.jpg",
    "imageAlt": "Portada de El traidor del siglo, de John le Carré",
    "amazonUrl": "https://www.amazon.es/s?k=El%20traidor%20del%20siglo%20John%20le%20Carr%C3%A9&tag=libreriajerez-21"
  },
  {
    "slug": "tu-pasado-me-condena",
    "title": "Tu pasado me condena",
    "author": "Corín Tellado",
    "isbn": "978-8408018315",
    "price": 5.5,
    "genre": "Romántica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408018315-L.jpg",
    "imageAlt": "Portada de Tu pasado me condena, de Corín Tellado",
    "amazonUrl": "https://www.amazon.es/s?k=Tu%20pasado%20me%20condena%20Cor%C3%ADn%20Tellado&tag=libreriajerez-21"
  },
  {
    "slug": "toma-mi-corazon",
    "title": "Toma mi corazón",
    "author": "Walter Dresel",
    "isbn": "978-8496748446",
    "price": 5.5,
    "genre": "Autoayuda / Desarrollo",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496748446-L.jpg",
    "imageAlt": "Portada de Toma mi corazón, de Walter Dresel",
    "amazonUrl": "https://www.amazon.es/s?k=Toma%20mi%20coraz%C3%B3n%20Walter%20Dresel&tag=libreriajerez-21"
  },
  {
    "slug": "el-secreto",
    "title": "El secreto",
    "author": "Rhonda Byrne",
    "isbn": "978-8479536442",
    "price": 5.5,
    "genre": "Autoayuda",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788479536442-L.jpg",
    "imageAlt": "Portada de El secreto, de Rhonda Byrne",
    "amazonUrl": "https://www.amazon.es/s?k=El%20secreto%20Rhonda%20Byrne&tag=libreriajerez-21"
  },
  {
    "slug": "la-bodega",
    "title": "La bodega",
    "author": "Vicente Blasco Ibáñez",
    "isbn": "978-8420663364",
    "price": 5.5,
    "genre": "Ficción histórica / Clásicos",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420663364-L.jpg",
    "imageAlt": "Portada de La bodega, de Vicente Blasco Ibáñez",
    "amazonUrl": "https://www.amazon.es/s?k=La%20bodega%20Vicente%20Blasco%20Ib%C3%A1%C3%B1ez&tag=libreriajerez-21"
  },
  {
    "slug": "la-tregua",
    "title": "La tregua",
    "author": "Mario Benedetti",
    "isbn": "978-8420658933",
    "price": 5.5,
    "genre": "Narrativa contemporánea",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420658933-L.jpg",
    "imageAlt": "Portada de La tregua, de Mario Benedetti",
    "amazonUrl": "https://www.amazon.es/s?k=La%20tregua%20Mario%20Benedetti&tag=libreriajerez-21"
  },
  {
    "slug": "cuentos-de-navidad",
    "title": "Cuentos de Navidad",
    "author": "Charles Dickens",
    "isbn": "978-8491050216",
    "price": 5.5,
    "genre": "Clásicos",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788491050216-L.jpg",
    "imageAlt": "Portada de Cuentos de Navidad, de Charles Dickens",
    "amazonUrl": "https://www.amazon.es/s?k=Cuentos%20de%20Navidad%20Charles%20Dickens&tag=libreriajerez-21"
  },
  {
    "slug": "una-pluma-con-historia",
    "title": "Una pluma con historia",
    "author": "Beatriz Doumerc",
    "isbn": "978-8420712796",
    "price": 4.9,
    "genre": "Infantil / Juvenil",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420712796-L.jpg",
    "imageAlt": "Portada de Una pluma con historia, de Beatriz Doumerc",
    "amazonUrl": "https://www.amazon.es/s?k=Una%20pluma%20con%20historia%20Beatriz%20Doumerc&tag=libreriajerez-21"
  },
  {
    "slug": "destino-prohibido",
    "title": "Destino prohibido",
    "author": "Xavier Bertran",
    "isbn": "978-8408061489",
    "price": 5.9,
    "genre": "Narrativa contemporánea",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408061489-L.jpg",
    "imageAlt": "Portada de Destino prohibido, de Xavier Bertran",
    "amazonUrl": "https://www.amazon.es/s?k=Destino%20prohibido%20Xavier%20Bertran&tag=libreriajerez-21"
  },
  {
    "slug": "joyas-robadas",
    "title": "Joyas robadas",
    "author": "Juan José Plans",
    "isbn": "978-8420738413",
    "price": 6.5,
    "genre": "Misterio / Policiaco",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420738413-L.jpg",
    "imageAlt": "Portada de Joyas robadas, de Juan José Plans",
    "amazonUrl": "https://www.amazon.es/s?k=Joyas%20robadas%20Juan%20Jos%C3%A9%20Plans&tag=libreriajerez-21"
  },
  {
    "slug": "el-desahucio",
    "title": "El desahucio",
    "author": "Ignacio Aldecoa",
    "isbn": "978-8420658780",
    "price": 5.9,
    "genre": "Narrativa / Cuentos",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420658780-L.jpg",
    "imageAlt": "Portada de El desahucio, de Ignacio Aldecoa",
    "amazonUrl": "https://www.amazon.es/s?k=El%20desahucio%20Ignacio%20Aldecoa&tag=libreriajerez-21"
  },
  {
    "slug": "el-eunuco-del-rey",
    "title": "El eunuco del rey",
    "author": "José de Cora",
    "isbn": "978-8497343299",
    "price": 6.5,
    "genre": "Novela histórica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497343299-L.jpg",
    "imageAlt": "Portada de El eunuco del rey, de José de Cora",
    "amazonUrl": "https://www.amazon.es/s?k=El%20eunuco%20del%20rey%20Jos%C3%A9%20de%20Cora&tag=libreriajerez-21"
  },
  {
    "slug": "la-maldicion-del-brujo-leopardo",
    "title": "La maldición del brujo-leopardo",
    "author": "Heinz Delam",
    "isbn": "978-8421692226",
    "price": 4.9,
    "genre": "Juvenil / Aventuras",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788421692226-L.jpg",
    "imageAlt": "Portada de La maldición del brujo-leopardo, de Heinz Delam",
    "amazonUrl": "https://www.amazon.es/s?k=La%20maldici%C3%B3n%20del%20brujo-leopardo%20Heinz%20Delam&tag=libreriajerez-21"
  },
  {
    "slug": "pupila-de-aguila",
    "title": "Pupila de águila",
    "author": "Alfredo Gómez Cerdá",
    "isbn": "978-8467577785",
    "price": 4.9,
    "genre": "Juvenil",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788467577785-L.jpg",
    "imageAlt": "Portada de Pupila de águila, de Alfredo Gómez Cerdá",
    "amazonUrl": "https://www.amazon.es/s?k=Pupila%20de%20%C3%A1guila%20Alfredo%20G%C3%B3mez%20Cerd%C3%A1&tag=libreriajerez-21"
  },
  {
    "slug": "don-juan-tenorio",
    "title": "Don Juan Tenorio",
    "author": "José Zorrilla",
    "isbn": "978-8437604473",
    "price": 5.5,
    "genre": "Teatro clásico",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788437604473-L.jpg",
    "imageAlt": "Portada de Don Juan Tenorio, de José Zorrilla",
    "amazonUrl": "https://www.amazon.es/s?k=Don%20Juan%20Tenorio%20Jos%C3%A9%20Zorrilla&tag=libreriajerez-21"
  },
  {
    "slug": "medicos-y-verdugos-de-la-media-luna",
    "title": "Médicos y verdugos de la media luna",
    "author": "Daniel Botta Lobato",
    "isbn": "978-8496416567",
    "price": 22,
    "genre": "Ensayo histórico / Medicina",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496416567-L.jpg",
    "imageAlt": "Portada de Médicos y verdugos de la media luna, de Daniel Botta Lobato",
    "amazonUrl": "https://www.amazon.es/s?k=M%C3%A9dicos%20y%20verdugos%20de%20la%20media%20luna%20Daniel%20Botta%20Lobato&tag=libreriajerez-21"
  },
  {
    "slug": "campanas-de-duelo",
    "title": "Campanas de duelo",
    "author": "Artacho",
    "isbn": "978-8496106673",
    "price": 5.9,
    "genre": "Narrativa contemporánea",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496106673-L.jpg",
    "imageAlt": "Portada de Campanas de duelo, de Artacho",
    "amazonUrl": "https://www.amazon.es/s?k=Campanas%20de%20duelo%20Artacho&tag=libreriajerez-21"
  },
  {
    "slug": "bajo-la-estrella-polar",
    "title": "Bajo la estrella polar",
    "author": "Stef Penney",
    "isbn": "978-8498322637",
    "price": 6.5,
    "genre": "Thriller histórico / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788498322637-L.jpg",
    "imageAlt": "Portada de Bajo la estrella polar, de Stef Penney",
    "amazonUrl": "https://www.amazon.es/s?k=Bajo%20la%20estrella%20polar%20Stef%20Penney&tag=libreriajerez-21"
  },
  {
    "slug": "tierra-dividida",
    "title": "Tierra dividida",
    "author": "Ramón Muñoz",
    "isbn": "978-8496778405",
    "price": 6.5,
    "genre": "Novela histórica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496778405-L.jpg",
    "imageAlt": "Portada de Tierra dividida, de Ramón Muñoz",
    "amazonUrl": "https://www.amazon.es/s?k=Tierra%20dividida%20Ram%C3%B3n%20Mu%C3%B1oz&tag=libreriajerez-21"
  },
  {
    "slug": "la-piramide-de-barro",
    "title": "La pirámide de barro",
    "author": "Fabio Sorrentino",
    "isbn": "978-8496587397",
    "price": 6.5,
    "genre": "Misterio / Aventura",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496587397-L.jpg",
    "imageAlt": "Portada de La pirámide de barro, de Fabio Sorrentino",
    "amazonUrl": "https://www.amazon.es/s?k=La%20pir%C3%A1mide%20de%20barro%20Fabio%20Sorrentino&tag=libreriajerez-21"
  },
  {
    "slug": "muerte-lenta",
    "title": "Muerte lenta",
    "author": "Lucía Palermo",
    "isbn": "978-8493630652",
    "price": 6.5,
    "genre": "Thriller / Policiaco",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788493630652-L.jpg",
    "imageAlt": "Portada de Muerte lenta, de Lucía Palermo",
    "amazonUrl": "https://www.amazon.es/s?k=Muerte%20lenta%20Luc%C3%ADa%20Palermo&tag=libreriajerez-21"
  },
  {
    "slug": "la-cena-secreta",
    "title": "La cena secreta",
    "author": "Javier Sierra",
    "isbn": "978-8408070962",
    "price": 6.5,
    "genre": "Thriller histórico / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408070962-L.jpg",
    "imageAlt": "Portada de La cena secreta, de Javier Sierra",
    "amazonUrl": "https://www.amazon.es/s?k=La%20cena%20secreta%20Javier%20Sierra&tag=libreriajerez-21"
  },
  {
    "slug": "el-judio-de-qumran",
    "title": "El judío de Qumrán",
    "author": "Eliette Abécassis",
    "isbn": "978-8408031642",
    "price": 6.5,
    "genre": "Intriga histórica / Ficción",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408031642-L.jpg",
    "imageAlt": "Portada de El judío de Qumrán, de Eliette Abécassis",
    "amazonUrl": "https://www.amazon.es/s?k=El%20jud%C3%ADo%20de%20Qumr%C3%A1n%20Eliette%20Ab%C3%A9cassis&tag=libreriajerez-21"
  },
  {
    "slug": "catalina-la-grande",
    "title": "Catalina la Grande",
    "author": "Demetrio Nekrasov",
    "isbn": "978-8497341851",
    "price": 7.5,
    "genre": "Biografía / Historia",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497341851-L.jpg",
    "imageAlt": "Portada de Catalina la Grande, de Demetrio Nekrasov",
    "amazonUrl": "https://www.amazon.es/s?k=Catalina%20la%20Grande%20Demetrio%20Nekrasov&tag=libreriajerez-21"
  },
  {
    "slug": "maria-antonieta",
    "title": "María Antonieta",
    "author": "Edmond de Goncourt",
    "isbn": "978-8496106093",
    "price": 7.5,
    "genre": "Biografía histórica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496106093-L.jpg",
    "imageAlt": "Portada de María Antonieta, de Edmond de Goncourt",
    "amazonUrl": "https://www.amazon.es/s?k=Mar%C3%ADa%20Antonieta%20Edmond%20de%20Goncourt&tag=libreriajerez-21"
  },
  {
    "slug": "origen-perdido",
    "title": "Origen perdido",
    "author": "Matilde Asensi",
    "isbn": "978-8408053675",
    "price": 5.9,
    "genre": "Aventuras / Intriga",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408053675-L.jpg",
    "imageAlt": "Portada de Origen perdido, de Matilde Asensi",
    "amazonUrl": "https://www.amazon.es/s?k=Origen%20perdido%20Matilde%20Asensi&tag=libreriajerez-21"
  },
  {
    "slug": "inferno",
    "title": "Inferno",
    "author": "Dan Brown",
    "isbn": "978-8408114178",
    "price": 4.9,
    "genre": "Thriller y misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408114178-L.jpg",
    "imageAlt": "Portada de Inferno, de Dan Brown",
    "amazonUrl": "https://www.amazon.es/s?k=Inferno%20Dan%20Brown&tag=libreriajerez-21"
  },
  {
    "slug": "historia-universal-vol-1",
    "title": "Historia universal (Vol. 1)",
    "author": "J. M. Roberts",
    "isbn": "978-8484328896",
    "price": 9.5,
    "genre": "Historia / Ensayo",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788484328896-L.jpg",
    "imageAlt": "Portada de Historia universal (Vol. 1), de J. M. Roberts",
    "amazonUrl": "https://www.amazon.es/s?k=Historia%20universal%20(Vol.%201)%20J.%20M.%20Roberts&tag=libreriajerez-21"
  },
  {
    "slug": "redencion",
    "title": "Redención",
    "author": "Leon Uris",
    "isbn": "978-8401326417",
    "price": 6.5,
    "genre": "Ficción histórica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788401326417-L.jpg",
    "imageAlt": "Portada de Redención, de Leon Uris",
    "amazonUrl": "https://www.amazon.es/s?k=Redenci%C3%B3n%20Leon%20Uris&tag=libreriajerez-21"
  },
  {
    "slug": "coltan",
    "title": "Coltán",
    "author": "Alberto Vázquez-Figueroa",
    "isbn": "978-8499890470",
    "price": 6.5,
    "genre": "Thriller contemporáneo",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788499890470-L.jpg",
    "imageAlt": "Portada de Coltán, de Alberto Vázquez-Figueroa",
    "amazonUrl": "https://www.amazon.es/s?k=Colt%C3%A1n%20Alberto%20V%C3%A1zquez-Figueroa&tag=libreriajerez-21"
  },
  {
    "slug": "incidente-en-la-bahia",
    "title": "Incidente en la bahía",
    "author": "Serafín Grijalba",
    "isbn": "978-8496416116",
    "price": 6.5,
    "genre": "Novela negra / Suspense",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496416116-L.jpg",
    "imageAlt": "Portada de Incidente en la bahía, de Serafín Grijalba",
    "amazonUrl": "https://www.amazon.es/s?k=Incidente%20en%20la%20bah%C3%ADa%20Seraf%C3%ADn%20Grijalba&tag=libreriajerez-21"
  },
  {
    "slug": "isabel-la-catolica-la-conquista-del-poder",
    "title": "Isabel la Católica: La conquista del poder",
    "author": "Michèle Maurel",
    "isbn": "978-8497342674",
    "price": 7.5,
    "genre": "Novela histórica / Biografía",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497342674-L.jpg",
    "imageAlt": "Portada de Isabel la Católica: La conquista del poder, de Michèle Maurel",
    "amazonUrl": "https://www.amazon.es/s?k=Isabel%20la%20Cat%C3%B3lica%3A%20La%20conquista%20del%20poder%20Mich%C3%A8le%20Maurel&tag=libreriajerez-21"
  },
  {
    "slug": "el-afgano",
    "title": "El afgano",
    "author": "Frederick Forsyth",
    "isbn": "978-8401336058",
    "price": 6.5,
    "genre": "Espionaje / Suspense",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788401336058-L.jpg",
    "imageAlt": "Portada de El afgano, de Frederick Forsyth",
    "amazonUrl": "https://www.amazon.es/s?k=El%20afgano%20Frederick%20Forsyth&tag=libreriajerez-21"
  },
  {
    "slug": "la-regata",
    "title": "La regata",
    "author": "Manuel Vicent",
    "isbn": "978-8420432328",
    "price": 5.9,
    "genre": "Narrativa contemporánea",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420432328-L.jpg",
    "imageAlt": "Portada de La regata, de Manuel Vicent",
    "amazonUrl": "https://www.amazon.es/s?k=La%20regata%20Manuel%20Vicent&tag=libreriajerez-21"
  },
  {
    "slug": "berlin-la-caida-1945",
    "title": "Berlín: La caída 1945",
    "author": "Antony Beevor",
    "isbn": "978-8484323655",
    "price": 11,
    "genre": "Historia / Segunda Guerra Mundial",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788484323655-L.jpg",
    "imageAlt": "Portada de Berlín: La caída 1945, de Antony Beevor",
    "amazonUrl": "https://www.amazon.es/s?k=Berl%C3%ADn%3A%20La%20ca%C3%ADda%201945%20Antony%20Beevor&tag=libreriajerez-21"
  },
  {
    "slug": "el-club-dante",
    "title": "El club Dante",
    "author": "Matthew Pearl",
    "isbn": "978-8408052135",
    "price": 6.5,
    "genre": "Thriller histórico / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408052135-L.jpg",
    "imageAlt": "Portada de El club Dante, de Matthew Pearl",
    "amazonUrl": "https://www.amazon.es/s?k=El%20club%20Dante%20Matthew%20Pearl&tag=libreriajerez-21"
  },
  {
    "slug": "el-asedio",
    "title": "El asedio",
    "author": "Arturo Pérez-Reverte",
    "isbn": "978-8420405629",
    "price": 7.9,
    "genre": "Novela histórica / Intriga",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420405629-L.jpg",
    "imageAlt": "Portada de El asedio, de Arturo Pérez-Reverte",
    "amazonUrl": "https://www.amazon.es/s?k=El%20asedio%20Arturo%20P%C3%A9rez-Reverte&tag=libreriajerez-21"
  },
  {
    "slug": "de-algeciras-a-estambul",
    "title": "De Algeciras a Estambul",
    "author": "Francisco Roldán",
    "isbn": "978-8496416390",
    "price": 5.9,
    "genre": "Crónica de viajes / Narrativa",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496416390-L.jpg",
    "imageAlt": "Portada de De Algeciras a Estambul, de Francisco Roldán",
    "amazonUrl": "https://www.amazon.es/s?k=De%20Algeciras%20a%20Estambul%20Francisco%20Rold%C3%A1n&tag=libreriajerez-21"
  },
  {
    "slug": "felipe-ii-carlos-v-el-emperador",
    "title": "Felipe II: Carlos V, el emperador",
    "author": "Carlos Bourbon-Parma",
    "isbn": "978-8497340892",
    "price": 9.5,
    "genre": "Biografía / Ensayo histórico",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497340892-L.jpg",
    "imageAlt": "Portada de Felipe II: Carlos V, el emperador, de Carlos Bourbon-Parma",
    "amazonUrl": "https://www.amazon.es/s?k=Felipe%20II%3A%20Carlos%20V%2C%20el%20emperador%20Carlos%20Bourbon-Parma&tag=libreriajerez-21"
  },
  {
    "slug": "falco",
    "title": "Falcó",
    "author": "Arturo Pérez-Reverte",
    "isbn": "978-8420419688",
    "price": 7.5,
    "genre": "Espionaje / Thriller",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420419688-L.jpg",
    "imageAlt": "Portada de Falcó, de Arturo Pérez-Reverte",
    "amazonUrl": "https://www.amazon.es/s?k=Falc%C3%B3%20Arturo%20P%C3%A9rez-Reverte&tag=libreriajerez-21"
  },
  {
    "slug": "por-que-fracasan-los-paises",
    "title": "Por qué fracasan los países",
    "author": "Daron Acemoglu y James A. Robinson",
    "isbn": "978-8423412662",
    "price": 11.5,
    "genre": "Ensayo económico / Política",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788423412662-L.jpg",
    "imageAlt": "Portada de Por qué fracasan los países, de Daron Acemoglu y James A. Robinson",
    "amazonUrl": "https://www.amazon.es/s?k=Por%20qu%C3%A9%20fracasan%20los%20pa%C3%ADses%20Daron%20Acemoglu%20y%20James%20A.%20Robinson&tag=libreriajerez-21"
  },
  {
    "slug": "la-comitiva-de-los-embusteros",
    "title": "La comitiva de los embusteros",
    "author": "Karen Maitland",
    "isbn": "978-8408088486",
    "price": 6.5,
    "genre": "Ficción histórica / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408088486-L.jpg",
    "imageAlt": "Portada de La comitiva de los embusteros, de Karen Maitland",
    "amazonUrl": "https://www.amazon.es/s?k=La%20comitiva%20de%20los%20embusteros%20Karen%20Maitland&tag=libreriajerez-21"
  },
  {
    "slug": "cornelia-gades",
    "title": "Cornelia Gades",
    "author": "Juan Eslava Galán",
    "isbn": "978-8408073536",
    "price": 6.5,
    "genre": "Novela histórica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408073536-L.jpg",
    "imageAlt": "Portada de Cornelia Gades, de Juan Eslava Galán",
    "amazonUrl": "https://www.amazon.es/s?k=Cornelia%20Gades%20Juan%20Eslava%20Gal%C3%A1n&tag=libreriajerez-21"
  },
  {
    "slug": "sabotaje",
    "title": "Sabotaje",
    "author": "Arturo Pérez-Reverte",
    "isbn": "978-8420435190",
    "price": 7.5,
    "genre": "Espionaje / Ficción histórica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420435190-L.jpg",
    "imageAlt": "Portada de Sabotaje, de Arturo Pérez-Reverte",
    "amazonUrl": "https://www.amazon.es/s?k=Sabotaje%20Arturo%20P%C3%A9rez-Reverte&tag=libreriajerez-21"
  },
  {
    "slug": "cincuenta-sombras-de-grey",
    "title": "Cincuenta sombras de Grey",
    "author": "E. L. James",
    "isbn": "978-8425348839",
    "price": 4.5,
    "genre": "Novela erótica / Romance",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788425348839-L.jpg",
    "imageAlt": "Portada de Cincuenta sombras de Grey, de E. L. James",
    "amazonUrl": "https://www.amazon.es/s?k=Cincuenta%20sombras%20de%20Grey%20E.%20L.%20James&tag=libreriajerez-21"
  },
  {
    "slug": "angeles-y-demonios",
    "title": "Ángeles y demonios",
    "author": "Dan Brown",
    "isbn": "978-8408072706",
    "price": 4.9,
    "genre": "Thriller / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408072706-L.jpg",
    "imageAlt": "Portada de Ángeles y demonios, de Dan Brown",
    "amazonUrl": "https://www.amazon.es/s?k=%C3%81ngeles%20y%20demonios%20Dan%20Brown&tag=libreriajerez-21"
  },
  {
    "slug": "trilogia-de-nueva-york",
    "title": "Trilogía de Nueva York",
    "author": "Paul Auster",
    "isbn": "978-8433966575",
    "price": 6.5,
    "genre": "Narrativa / Policiaco postmoderno",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788433966575-L.jpg",
    "imageAlt": "Portada de Trilogía de Nueva York, de Paul Auster",
    "amazonUrl": "https://www.amazon.es/s?k=Trilog%C3%ADa%20de%20Nueva%20York%20Paul%20Auster&tag=libreriajerez-21"
  },
  {
    "slug": "latidos",
    "title": "Latidos",
    "author": "Luz Gabás",
    "isbn": "978-8408216346",
    "price": 7.5,
    "genre": "Narrativa / Ficción romántica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408216346-L.jpg",
    "imageAlt": "Portada de Latidos, de Luz Gabás",
    "amazonUrl": "https://www.amazon.es/s?k=Latidos%20Luz%20Gab%C3%A1s&tag=libreriajerez-21"
  },
  {
    "slug": "tratamiento-mortal",
    "title": "Tratamiento mortal",
    "author": "Robin Cook",
    "isbn": "978-8497594950",
    "price": 6.5,
    "genre": "Thriller médico",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497594950-L.jpg",
    "imageAlt": "Portada de Tratamiento mortal, de Robin Cook",
    "amazonUrl": "https://www.amazon.es/s?k=Tratamiento%20mortal%20Robin%20Cook&tag=libreriajerez-21"
  },
  {
    "slug": "manipulacion",
    "title": "Manipulación",
    "author": "Robin Cook",
    "isbn": "978-8497592499",
    "price": 6.5,
    "genre": "Thriller médico",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497592499-L.jpg",
    "imageAlt": "Portada de Manipulación, de Robin Cook",
    "amazonUrl": "https://www.amazon.es/s?k=Manipulaci%C3%B3n%20Robin%20Cook&tag=libreriajerez-21"
  },
  {
    "slug": "cortar-por-lo-sano",
    "title": "Cortar por lo sano",
    "author": "Rosa Balmaceda Paturzo",
    "isbn": "978-8496416802",
    "price": 5.9,
    "genre": "Narrativa contemporánea",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496416802-L.jpg",
    "imageAlt": "Portada de Cortar por lo sano, de Rosa Balmaceda Paturzo",
    "amazonUrl": "https://www.amazon.es/s?k=Cortar%20por%20lo%20sano%20Rosa%20Balmaceda%20Paturzo&tag=libreriajerez-21"
  },
  {
    "slug": "el-hotel-de-los-horrores",
    "title": "El hotel de los horrores",
    "author": "Wilkie Collins",
    "isbn": "978-8474261899",
    "price": 6.5,
    "genre": "Terror gótico / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788474261899-L.jpg",
    "imageAlt": "Portada de El hotel de los horrores, de Wilkie Collins",
    "amazonUrl": "https://www.amazon.es/s?k=El%20hotel%20de%20los%20horrores%20Wilkie%20Collins&tag=libreriajerez-21"
  },
  {
    "slug": "la-confesion-de-un-clerigo-anglicano",
    "title": "La confesión de un clérigo anglicano",
    "author": "Wilkie Collins",
    "isbn": "978-8496416048",
    "price": 5.5,
    "genre": "Clásicos / Ficción",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496416048-L.jpg",
    "imageAlt": "Portada de La confesión de un clérigo anglicano, de Wilkie Collins",
    "amazonUrl": "https://www.amazon.es/s?k=La%20confesi%C3%B3n%20de%20un%20cl%C3%A9rigo%20anglicano%20Wilkie%20Collins&tag=libreriajerez-21"
  },
  {
    "slug": "la-noche-de-la-verdad",
    "title": "La noche de la verdad",
    "author": "Mary Higgins Clark",
    "isbn": "978-8497597142",
    "price": 6.5,
    "genre": "Suspense / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497597142-L.jpg",
    "imageAlt": "Portada de La noche de la verdad, de Mary Higgins Clark",
    "amazonUrl": "https://www.amazon.es/s?k=La%20noche%20de%20la%20verdad%20Mary%20Higgins%20Clark&tag=libreriajerez-21"
  },
  {
    "slug": "luna-de-invierno",
    "title": "Luna de invierno",
    "author": "Dean R. Koontz",
    "isbn": "978-8401326097",
    "price": 6.5,
    "genre": "Terror / Suspense",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788401326097-L.jpg",
    "imageAlt": "Portada de Luna de invierno, de Dean R. Koontz",
    "amazonUrl": "https://www.amazon.es/s?k=Luna%20de%20invierno%20Dean%20R.%20Koontz&tag=libreriajerez-21"
  },
  {
    "slug": "oclusion-y-anatomia-dental",
    "title": "Oclusión y anatomía dental",
    "author": "Enrico Steger",
    "isbn": "978-8485257324",
    "price": 22,
    "genre": "Medicina / Odontología",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788485257324-L.jpg",
    "imageAlt": "Portada de Oclusión y anatomía dental, de Enrico Steger",
    "amazonUrl": "https://www.amazon.es/s?k=Oclusi%C3%B3n%20y%20anatom%C3%ADa%20dental%20Enrico%20Steger&tag=libreriajerez-21"
  },
  {
    "slug": "alcanzar-la-serenidad",
    "title": "Alcanzar la serenidad",
    "author": "John C. Maxwell",
    "isbn": "978-8408064978",
    "price": 5.5,
    "genre": "Autoayuda / Liderazgo",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408064978-L.jpg",
    "imageAlt": "Portada de Alcanzar la serenidad, de John C. Maxwell",
    "amazonUrl": "https://www.amazon.es/s?k=Alcanzar%20la%20serenidad%20John%20C.%20Maxwell&tag=libreriajerez-21"
  },
  {
    "slug": "a-ti-que-te-importa",
    "title": "¿A ti qué te importa?",
    "author": "Megan Maxwell",
    "isbn": "978-8408118398",
    "price": 5.5,
    "genre": "Romántica / Erótica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408118398-L.jpg",
    "imageAlt": "Portada de ¿A ti qué te importa?, de Megan Maxwell",
    "amazonUrl": "https://www.amazon.es/s?k=%C2%BFA%20ti%20qu%C3%A9%20te%20importa%3F%20Megan%20Maxwell&tag=libreriajerez-21"
  },
  {
    "slug": "los-hombres-las-prefieren-rubias",
    "title": "Los hombres las prefieren rubias",
    "author": "Anita Loos",
    "isbn": "978-8497931885",
    "price": 5.5,
    "genre": "Humor / Clásicos",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788497931885-L.jpg",
    "imageAlt": "Portada de Los hombres las prefieren rubias, de Anita Loos",
    "amazonUrl": "https://www.amazon.es/s?k=Los%20hombres%20las%20prefieren%20rubias%20Anita%20Loos&tag=libreriajerez-21"
  },
  {
    "slug": "desde-mi-cielo",
    "title": "Desde mi cielo",
    "author": "Alice Sebold",
    "isbn": "978-8483835012",
    "price": 5.9,
    "genre": "Drama / Narrativa",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788483835012-L.jpg",
    "imageAlt": "Portada de Desde mi cielo, de Alice Sebold",
    "amazonUrl": "https://www.amazon.es/s?k=Desde%20mi%20cielo%20Alice%20Sebold&tag=libreriajerez-21"
  },
  {
    "slug": "el-caso-del-ultimo-crimen",
    "title": "El caso del último crimen",
    "author": "Peter Lovesey",
    "isbn": "978-8422619420",
    "price": 6.5,
    "genre": "Policiaco / Novela negra",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788422619420-L.jpg",
    "imageAlt": "Portada de El caso del último crimen, de Peter Lovesey",
    "amazonUrl": "https://www.amazon.es/s?k=El%20caso%20del%20%C3%BAltimo%20crimen%20Peter%20Lovesey&tag=libreriajerez-21"
  },
  {
    "slug": "hechizada",
    "title": "Hechizada",
    "author": "Marian Keyes",
    "isbn": "978-8401337093",
    "price": 5.5,
    "genre": "Romántica / Comedia",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788401337093-L.jpg",
    "imageAlt": "Portada de Hechizada, de Marian Keyes",
    "amazonUrl": "https://www.amazon.es/s?k=Hechizada%20Marian%20Keyes&tag=libreriajerez-21"
  },
  {
    "slug": "el-enigma-del-cuatro",
    "title": "El enigma del cuatro",
    "author": "Ian Caldwell y Dustin Thomason",
    "isbn": "978-8401335358",
    "price": 6.5,
    "genre": "Thriller histórico / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788401335358-L.jpg",
    "imageAlt": "Portada de El enigma del cuatro, de Ian Caldwell y Dustin Thomason",
    "amazonUrl": "https://www.amazon.es/s?k=El%20enigma%20del%20cuatro%20Ian%20Caldwell%20y%20Dustin%20Thomason&tag=libreriajerez-21"
  },
  {
    "slug": "lo-que-el-dia-debe-a-la-noche",
    "title": "Lo que el día debe a la noche",
    "author": "Yasmina Khadra",
    "isbn": "978-8423341887",
    "price": 6.5,
    "genre": "Ficción histórica / Drama",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788423341887-L.jpg",
    "imageAlt": "Portada de Lo que el día debe a la noche, de Yasmina Khadra",
    "amazonUrl": "https://www.amazon.es/s?k=Lo%20que%20el%20d%C3%ADa%20debe%20a%20la%20noche%20Yasmina%20Khadra&tag=libreriajerez-21"
  },
  {
    "slug": "la-primera-noche",
    "title": "La primera noche",
    "author": "Marc Levy",
    "isbn": "978-8408092476",
    "price": 6.5,
    "genre": "Aventuras / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408092476-L.jpg",
    "imageAlt": "Portada de La primera noche, de Marc Levy",
    "amazonUrl": "https://www.amazon.es/s?k=La%20primera%20noche%20Marc%20Levy&tag=libreriajerez-21"
  },
  {
    "slug": "el-tiempo-entre-costuras",
    "title": "El tiempo entre costuras",
    "author": "María Dueñas",
    "isbn": "978-8484607373",
    "price": 7.5,
    "genre": "Novela histórica / Ficción",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788484607373-L.jpg",
    "imageAlt": "Portada de El tiempo entre costuras, de María Dueñas",
    "amazonUrl": "https://www.amazon.es/s?k=El%20tiempo%20entre%20costuras%20Mar%C3%ADa%20Due%C3%B1as&tag=libreriajerez-21"
  },
  {
    "slug": "un-mundo-sin-fin",
    "title": "Un mundo sin fin",
    "author": "Ken Follett",
    "isbn": "978-8401336560",
    "price": 8.5,
    "genre": "Ficción histórica",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788401336560-L.jpg",
    "imageAlt": "Portada de Un mundo sin fin, de Ken Follett",
    "amazonUrl": "https://www.amazon.es/s?k=Un%20mundo%20sin%20fin%20Ken%20Follett&tag=libreriajerez-21"
  },
  {
    "slug": "el-codigo-da-vinci",
    "title": "El código Da Vinci",
    "author": "Dan Brown",
    "isbn": "978-8408052944",
    "price": 4.9,
    "genre": "Thriller / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408052944-L.jpg",
    "imageAlt": "Portada de El código Da Vinci, de Dan Brown",
    "amazonUrl": "https://www.amazon.es/s?k=El%20c%C3%B3digo%20Da%20Vinci%20Dan%20Brown&tag=libreriajerez-21"
  },
  {
    "slug": "la-hermandad-de-la-sabana-santa",
    "title": "La hermandad de la sábana santa",
    "author": "Julia Navarro",
    "isbn": "978-8401335266",
    "price": 6.5,
    "genre": "Thriller histórico / Misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788401335266-L.jpg",
    "imageAlt": "Portada de La hermandad de la sábana santa, de Julia Navarro",
    "amazonUrl": "https://www.amazon.es/s?k=La%20hermandad%20de%20la%20s%C3%A1bana%20santa%20Julia%20Navarro&tag=libreriajerez-21"
  },
  {
    "slug": "el-perro-de-los-baskerville",
    "title": "El perro de los Baskerville",
    "author": "Arthur Conan Doyle",
    "isbn": "978-8420663432",
    "price": 5.5,
    "genre": "Clásicos del misterio",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788420663432-L.jpg",
    "imageAlt": "Portada de El perro de los Baskerville, de Arthur Conan Doyle",
    "amazonUrl": "https://www.amazon.es/s?k=El%20perro%20de%20los%20Baskerville%20Arthur%20Conan%20Doyle&tag=libreriajerez-21"
  },
  {
    "slug": "el-factor-humano",
    "title": "El factor humano",
    "author": "Graham Greene",
    "isbn": "978-8432217111",
    "price": 6.5,
    "genre": "Espionaje / Suspense",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788432217111-L.jpg",
    "imageAlt": "Portada de El factor humano, de Graham Greene",
    "amazonUrl": "https://www.amazon.es/s?k=El%20factor%20humano%20Graham%20Greene&tag=libreriajerez-21"
  },
  {
    "slug": "el-jardin-de-verano",
    "title": "El jardín de verano",
    "author": "Paullina Simons",
    "isbn": "978-8496748460",
    "price": 6.5,
    "genre": "Ficción histórica / Romance",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788496748460-L.jpg",
    "imageAlt": "Portada de El jardín de verano, de Paullina Simons",
    "amazonUrl": "https://www.amazon.es/s?k=El%20jard%C3%ADn%20de%20verano%20Paullina%20Simons&tag=libreriajerez-21"
  },
  {
    "slug": "fuego-cruzado",
    "title": "Fuego cruzado",
    "author": "Paula Hawkins",
    "isbn": "978-8408246404",
    "price": 7.5,
    "genre": "Thriller / Suspense",
    "imageUrl": "https://covers.openlibrary.org/b/isbn/9788408246404-L.jpg",
    "imageAlt": "Portada de Fuego cruzado, de Paula Hawkins",
    "amazonUrl": "https://www.amazon.es/s?k=Fuego%20cruzado%20Paula%20Hawkins&tag=libreriajerez-21"
  }
];
