import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";

export default async function ReviewDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const review = await db.review.findFirst({ where: { slug, status: "PUBLISHED" }, include: { book: true } });
  if (!review) notFound();
  const hasUsedCopy = Boolean(review.book && review.book.stock > 0 && review.book.status === "PUBLISHED");
  return <main className="min-h-screen bg-[#f5f0e7] text-[#20322d]"><header className="mx-auto flex max-w-7xl items-center justify-between border-b border-[#d5cec2] px-5 py-5 lg:px-8"><Link className="brand text-xl font-bold" href="/">Segunda Vuelta <span>Libros</span></Link><Link href="/resenas" className="font-sans text-sm underline">Todas las reseñas</Link></header><article className="mx-auto grid max-w-6xl gap-12 px-5 py-16 lg:grid-cols-[.7fr_1.3fr] lg:py-24"><div><div className="review-cover large" style={{ backgroundImage: `url(${review.coverUrl ?? ""})` }} role="img" aria-label={review.coverAlt ?? "Portada de reseña"} /><p className="mt-5 font-sans text-xs uppercase tracking-[.15em] text-[#b85c43]">{review.publishedAt?.toLocaleDateString("es-ES", { dateStyle: "long" })}</p></div><div><p className="eyebrow">RESEÑA EDITORIAL</p><h1 className="text-5xl leading-none lg:text-7xl">{review.title}</h1><p className="mt-4 font-sans text-[#69746e]">Por {review.author}</p><div className="stars mt-6 text-xl">{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</div><div className="mt-12 border-y border-[#d5cec2] py-8"><h2 className="font-sans text-xs font-bold uppercase tracking-[.14em]">Sinopsis</h2><p className="mt-4 text-xl leading-relaxed">{review.synopsis}</p></div><div className="review-content mt-10 whitespace-pre-line font-sans text-base leading-8 text-[#4f5d55]">{review.content}</div><div className="review-actions mt-12">{hasUsedCopy ? <Link className="used-book-button" href="/">Comprar nuestro ejemplar usado · {Number(review.book?.price).toFixed(2).replace(".", ",")} EUR</Link> : <span className="muted-button">Ejemplar usado no disponible</span>}{review.amazonAffiliateUrl && <a className="amazon-button" href={review.amazonAffiliateUrl} target="_blank" rel="noopener noreferrer nofollow">Comprar nuevo en Amazon ↗</a>}</div><p className="mt-5 font-sans text-xs text-[#69746e]">Los enlaces a Amazon pueden generar una comisión para la librería, sin coste adicional para ti.</p>{review.instagramUrl && <a className="instagram-button mt-8" href={review.instagramUrl} target="_blank" rel="noopener noreferrer">Ver post o reel en Instagram ↗</a>}<div className="mt-10 flex gap-5 border-t border-[#d5cec2] pt-6 font-sans text-sm"><span>Compartir:</span><a href={`https://twitter.com/intent/tweet?text=${encodeURIComponent(review.title)}&url=${encodeURIComponent(`http://localhost:3000/resenas/${review.slug}`)}`} target="_blank" rel="noopener noreferrer">X</a><a href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(`http://localhost:3000/resenas/${review.slug}`)}`} target="_blank" rel="noopener noreferrer">Facebook</a></div></div></article></main>;
}