import Link from "next/link";
import { Mail, MapPin, Phone } from "lucide-react";

const instagramUrl = "https://www.instagram.com/escondida_en_un_libro_?igsi=MWpoanFsZjh0MWRzYg==";
export function Footer() {
  return <footer className="professional-footer"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 lg:grid-cols-4 lg:px-8"><div><Link href="/" className="footer-logo"><span>SvL</span><strong>Segunda Vuelta</strong><em>Libros</em></Link><p>Historias con pasado, lectores por conocer. Desde Jerez para toda la península.</p><div className="footer-social"><a href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer" aria-label="Facebook"><FacebookMark /></a><a href={instagramUrl} target="_blank" rel="noopener noreferrer" aria-label="Instagram"><InstagramMark /></a></div><small>© 2026 Segunda Vuelta Libros</small></div><div><h3>Contacto</h3><a href="tel:+34956000000"><Phone size={15} /> +34 956 000 000</a><a href="mailto:info@segundavuelta.es"><Mail size={15} /> info@segundavuelta.es</a><a href="#contacto"><MapPin size={15} /> Jerez de la Frontera</a></div><div><h3>Páginas legales</h3><Link href="#faq">Preguntas frecuentes</Link><Link href="#envios">Gastos de envío</Link><Link href="#devoluciones">Devoluciones</Link><Link href="#legal">Aviso legal</Link><Link href="#privacidad">Privacidad</Link></div><div><h3>Atención al cliente</h3><Link href="/resenas">Blog y reseñas</Link><Link href="#generos">Categorías de libros</Link><Link href="#vender">Vender mis libros</Link><Link href="#contacto">Formulario de contacto</Link></div></div></footer>;
}

function InstagramMark() { return <svg aria-hidden="true" className="social-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="3" y="3" width="18" height="18" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none" /></svg>; }
function FacebookMark() { return <span aria-hidden="true" className="facebook-mark">f</span>; }
