"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Check, ChevronDown, Heart, Menu, Search, ShoppingBag, Truck, X } from "lucide-react";

type StoreBook = { id: string; title: string; author: string; price: number; condition: string; imageUrl: string | null; imageAlt: string | null; category: string };
type StoreReview = { slug: string; title: string; author: string; rating: number; coverUrl: string | null; coverAlt: string | null; synopsis: string };
const conditionLabels: Record<string, string> = { LIKE_NEW: "Excelente", VERY_GOOD: "Muy buen estado", GOOD: "Buen estado", ACCEPTABLE: "Aceptable", DEFECTIVE: "Con defectos" };
const instagramUrl = "https://www.instagram.com/escondida_en_un_libro_?igsi=MWpoanFsZjh0MWRzYg==";

export function Storefront({ books, reviews }: { books: StoreBook[]; reviews: StoreReview[] }) {
  const [query, setQuery] = useState("");
  const [condition, setCondition] = useState("Todas");
  const [category, setCategory] = useState("Todos");
  const [price, setPrice] = useState("Cualquier precio");
  const [cart, setCart] = useState<string[]>([]);
  const [menuOpen, setMenuOpen] = useState(false);
  const [cartOpen, setCartOpen] = useState(false);
  const categories = ["Todos", ...Array.from(new Set(books.map((book) => book.category)))];
  const filteredBooks = useMemo(() => books.filter((book) => {
    const matchesQuery = `${book.title} ${book.author}`.toLowerCase().includes(query.toLowerCase());
    const matchesCondition = condition === "Todas" || conditionLabels[book.condition] === condition;
    const matchesCategory = category === "Todos" || book.category === category;
    const matchesPrice = price === "Cualquier precio" || (price === "Menos de 8 EUR" ? book.price < 8 : book.price >= 8);
    return matchesQuery && matchesCondition && matchesCategory && matchesPrice;
  }), [books, category, condition, price, query]);
  const addToCart = (bookId: string) => setCart((current) => current.includes(bookId) ? current : [...current, bookId]);
  const cartBooks = books.filter((book) => cart.includes(book.id));
  const recommended = books[0];

  return <main className="min-h-screen bg-[#FBF9F5] text-[#1F2421]">
    <div className="demo-ribbon">CATÁLOGO DE DEMOSTRACIÓN · DATOS FICTICIOS</div>
    <header className="site-header mx-auto max-w-7xl px-5 py-5 lg:px-8"><button className="mobile-menu-button lg:hidden" aria-label={menuOpen ? "Cerrar menú" : "Abrir menú"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button><Link href="/" className="brand-lockup"><img src="/logo.png" alt="" className="brand-logo" onError={(event) => { event.currentTarget.style.display = "none"; event.currentTarget.nextElementSibling?.removeAttribute("hidden"); }} /><span className="brand-fallback" hidden><b>SvL</b><em>Segunda Vuelta Libros</em></span><span className="brand-text">Segunda Vuelta <span>Libros</span></span></Link><nav className={`${menuOpen ? "flex" : "hidden"} site-nav absolute left-0 top-[106px] z-20 w-full flex-col gap-5 bg-[#FBF9F5] px-6 py-6 text-sm lg:static lg:flex lg:w-auto lg:flex-row lg:bg-transparent lg:p-0`}><a href="#catalogo">Catálogo</a><a href="#generos">Géneros</a><a href="#novedades">Recién llegados</a><Link href="/resenas">Reseñas</Link><a href="#vender">Vender mis libros</a><a href="#nosotros">Sobre nosotros</a></nav><div className="flex items-center gap-5"><a className="social-link" href={instagramUrl} target="_blank" rel="noopener noreferrer" aria-label="Síguenos en Instagram"><InstagramMark /></a><button className="relative flex items-center gap-2 text-sm" aria-label={`Abrir carrito, ${cart.length} libros`} onClick={() => setCartOpen(!cartOpen)}><ShoppingBag size={19} /><span className="hidden sm:inline">Carrito</span>{cart.length > 0 && <b className="cart-count">{cart.length}</b>}</button></div></header>
    {cartOpen && <aside className="cart-drawer" aria-label="Carrito"><div className="flex items-center justify-between"><h2>Tu carrito</h2><button aria-label="Cerrar carrito" onClick={() => setCartOpen(false)}><X size={20} /></button></div>{cartBooks.length ? cartBooks.map((book) => <div className="cart-line" key={book.id}><span>{book.title}</span><strong>{book.price.toFixed(2).replace(".", ",")} EUR</strong></div>) : <p>Tu carrito está vacío.</p>}<small>El checkout estará disponible en una fase posterior.</small></aside>}
    <section id="inicio" className="hero-section mx-auto grid max-w-7xl gap-8 px-5 pb-20 pt-16 md:grid-cols-12 md:items-center lg:gap-12 lg:px-8 lg:pb-28 lg:pt-24"><div className="md:col-span-7"><p className="eyebrow mb-6">UNA SEGUNDA VIDA PARA CADA HISTORIA</p><h1 className="leading-tight">Historias que aún tienen mucho que decir.</h1><p className="hero-copy mb-6">Libros usados escogidos en Jerez, descritos sin rodeos y preparados para encontrar a su próxima persona lectora.</p><form className="search-box my-6" onSubmit={(event) => event.preventDefault()}><Search size={21} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Busca por título o autor" aria-label="Buscar por título o autor" /><button type="submit">Buscar</button></form><div className="category-pills gap-4" id="generos">{categories.map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div></div><div className="md:col-span-5"><HeroFeature recommended={recommended} onAdd={addToCart} /></div></section>
    <section id="novedades" className="content-section mx-auto max-w-7xl px-5 py-8 lg:px-8"><div className="section-title"><div><p className="eyebrow">LO ÚLTIMO EN LLEGAR</p><h2>Novedades</h2></div><a href="#catalogo">Ver todo <span>→</span></a></div><BookGrid books={books.slice(0, 4)} onAdd={addToCart} /></section>
    <section className="reviews-section content-section mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="section-title"><div><p className="eyebrow">CLUB DE LECTURA</p><h2>Últimas reseñas</h2></div><Link href="/resenas">Ver todas <span>→</span></Link></div>{reviews.length ? <div className="review-grid">{reviews.map((review) => <Link className="review-card" href={`/resenas/${review.slug}`} key={review.slug}><div className="review-cover" style={{ backgroundImage: `url(${review.coverUrl ?? ""})` }} role="img" aria-label={review.coverAlt ?? "Portada de reseña"} /><div className="review-card-copy"><div className="stars">{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</div><h3>{review.title}</h3><p>{review.author}</p><span>Leer reseña</span></div></Link>)}</div> : <p className="empty-state">Pronto compartiremos nuevas lecturas.</p>}</section>
    <section id="catalogo" className="catalog-section mx-auto max-w-7xl scroll-mt-10 px-5 py-16 lg:px-8"><div className="section-title"><div><p className="eyebrow">EXPLORA LA ESTANTERÍA</p><h2>Libros de segunda mano</h2></div><span className="result-count">{filteredBooks.length} ejemplares</span></div><div className="catalog-layout"><aside className="filters"><div className="flex items-center justify-between"><h3>Filtrar por</h3><button className="text-xs underline" onClick={() => { setCategory("Todos"); setCondition("Todas"); setPrice("Cualquier precio"); }}>Limpiar</button></div><label>Género<select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Precio<select value={price} onChange={(event) => setPrice(event.target.value)}><option>Cualquier precio</option><option>Menos de 8 EUR</option><option>8 EUR o más</option></select></label><label>Estado<select value={condition} onChange={(event) => setCondition(event.target.value)}><option>Todas</option>{Object.values(conditionLabels).map((item) => <option key={item}>{item}</option>)}</select></label></aside><div><BookGrid books={filteredBooks} onAdd={addToCart} /></div></div></section>
    <section id="nosotros" className="benefits-band"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="eyebrow">COMPRAR CON SENTIDO</p><h2>Una buena historia merece más de una oportunidad.</h2><div className="benefit-grid"><Benefit icon={<Check />} title="Estado claro" text="Cada ejemplar se revisa y se describe con honestidad." /><Benefit icon={<Heart />} title="Consumo consciente" text="Alargar la vida de un libro también evita que se desperdicie." /><Benefit icon={<Truck />} title="Envíos agrupados" text="Próximamente podrás reunir tus lecturas en un solo envío." /></div></div></section>
    <section className="instagram-banner"><div><p className="eyebrow">LA LIBRERÍA TAMBIÉN SE VE</p><h2>Videorreseñas, novedades y lecturas compartidas.</h2><p>Síguenos en Instagram para descubrir lo que acaba de llegar a la estantería.</p></div><a className="instagram-button" href={instagramUrl} target="_blank" rel="noopener noreferrer"><InstagramMark /> Seguir en Instagram</a></section>
    <footer id="vender" className="mx-auto max-w-7xl px-5 pb-10 pt-16 lg:px-8"><div className="footer-grid"><div><Link href="#inicio" className="brand text-xl font-bold">Segunda Vuelta <span>Libros</span></Link><p className="mt-4 max-w-xs font-sans text-sm leading-6 text-[#66706a]">Libros con pasado, lectores por conocer. Desde Jerez para toda la península.</p><a className="footer-instagram" href={instagramUrl} target="_blank" rel="noopener noreferrer"><InstagramMark /> Instagram</a></div><div><h3>Ayuda</h3><a href="#envios">Envíos</a><a href="#devoluciones">Devoluciones</a><a href="#contacto">Contacto</a></div><div><h3>La librería</h3><a href="#vender">Vender mis libros</a><a href="#nosotros">Sobre nosotros</a><a href="#legal">Aviso legal</a></div></div><p className="footer-bottom">© 2026 Segunda Vuelta Libros · Entorno de demostración · Sin pagos activos</p></footer>
  </main>;
}

function BookGrid({ books, onAdd }: { books: StoreBook[]; onAdd: (id: string) => void }) { return <div className="book-grid">{books.map((book) => <article className="book-card" key={book.id}><div className="book-cover" style={{ backgroundImage: `url(${book.imageUrl ?? ""})` }} role="img" aria-label={book.imageAlt ?? "Portada de demostración"}><span className="status-badge">{conditionLabels[book.condition]}</span><button className="quick-add" aria-label={`Añadir ${book.title} al carrito`} onClick={() => onAdd(book.id)}><ShoppingBag size={17} /></button></div><div className="book-info"><p className="book-author">{book.author}</p><h3>{book.title}</h3><div className="flex items-center justify-between"><strong>{book.price.toFixed(2).replace(".", ",")} EUR</strong><button className="add-link" onClick={() => onAdd(book.id)}>Añadir <ChevronDown size={14} /></button></div></div></article>)}</div>; }
function Benefit({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="benefit"><div>{icon}</div><h3>{title}</h3><p>{text}</p></div>; }
function InstagramMark() { return <svg aria-hidden="true" className="instagram-mark" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><rect x="3" y="3" width="18" height="18" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none" /></svg>; }
function HeroFeature({ recommended, onAdd }: { recommended?: StoreBook; onAdd: (id: string) => void }) { return <div className="hero-feature"><img src="/hero-banner.jpg" alt="Mesa cálida con libros y lectura" onError={(event) => { event.currentTarget.src = "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1200&q=85"; }} /><span className="hero-badge">Novedades de la Semana</span><div className="hero-feature-copy">{recommended ? <><p className="eyebrow">LIBRO RECOMENDADO</p><h2>{recommended.title}</h2><p>{recommended.author}</p><button onClick={() => onAdd(recommended.id)}>Ver ejemplar · {recommended.price.toFixed(2).replace(".", ",")} EUR <ShoppingBag size={15} /></button></> : <><p className="eyebrow">PRÓXIMAMENTE</p><h2>Nuevas lecturas en camino</h2></>}</div></div>; }
